plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: 'angular'
      releaseRules:
        - type: 'refactor'
          release: 'patch'
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSAO.txt"
  - "@semantic-release/gitlab"